name: CI - Test, Lint, Format, Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1 — Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 — Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"  # caches pip dependencies automatically

      # Step 3 — Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 pytest pytest-cov

      # Step 4 — Check formatting with Black
      - name: Check code formatting (black)
        run: black --check src tests

      # Step 5 — Check import order with isort
      - name: Check import sorting (isort)
        run: isort --check-only src tests

      # Step 6 — Lint with flake8
      - name: Run linting (flake8)
        run: flake8 src tests

      # Step 7 — Run unit tests with coverage
      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -v --cov=src --cov-report=xml --cov-report=term

      # Step 8 — Upload coverage report artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      # Step 9 — (Optional) Upload pytest HTML report if available
      - name: Upload pytest HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/
